### ISSUE TITLE
Support for other Github servers

### ISSUE THREAD

**Issue by cghersi** [cgrail/github-chrome-fullname#10]
Is there a chance to support more Github servers?
E.g. github.infra.hana.ondemand.com

**Comment by cgrail** [comment]
Hi @cghersi,

I've just send you a link by mail to the version of github infra. 
https://github.com/cgrail/github-chrome-fullname/compare/infra

Best regards,
Christian

**Comment by cghersi** [comment]
I confirm it perfectly works!
