### ISSUE TITLE
Recursive processing of names yields strange results

### ISSUE THREAD

**Issue by matushorvath** [cgrail/github-chrome-fullname#24]
Many of my colleagues have github.tools.sap full names set up in the form of "John Smith I012345". It seems this is/was the default way users were set up by some script, since around 15% of the people in my team include their i-number in their name. Mine was also that way until I changed it.

When this kind of user is processed by github-chrome-fullname, it tries to recursively substitute I012345 over and over again, until it hits some kind of limit. This causes usernames to be displayed as "John Smith John Smith John Smith John Smith John Smith John Smith John Smith John Smith John Smith I012345".

I propose that the behavior should be changed so that the name is not processed recursively, i.e. "I012345" should be replaced with "John Smith I012345", not with "John Smith John Smith John Smith John Smith John Smith John Smith John Smith John Smith John Smith I012345".

Some users who have their names set in this way on github.tools.sap (for testing): I055741 I505979 I802563

**Comment by Shegox** [comment]
This should have been addressed by #15 and in my local dev environment it is resolved as I encountered the same issue. 

It seems like in the current version (5.0.0) it isn't yet released. 
//cc @cgrail

**Comment by matushorvath** [comment]
@Shegox Thank you, I should have checked the PRs. @cgrail Is there a plan to release this fix?

**Comment by Shegox** [comment]
This should be now released: 
- Chrome: https://chrome.google.com/webstore/detail/name-instead-of-userid-fo/dpbnhgcdklhbhlemnffdbikcbfggcocd
- Firefox: https://addons.mozilla.org/de/firefox/addon/sap-github/

**Comment by matushorvath** [comment]
Verified the fix.
