### ISSUE TITLE
Do not replace inumber when Github ask to type the name of the repository when deleting

### ISSUE THREAD

**Issue by edonadei** [cgrail/github-chrome-fullname#30]
Hello, just an enhancement request, something that can be sometimes forgotten when a user tries to delete a repository

![image](https://user-images.githubusercontent.com/21025565/90247007-044d5a80-de36-11ea-9035-91f822e200c8.png)

Here, to finally delete my repository, i would have to understand that i have to type inumber/User-Guide. So the plugin should not make the replacement for this delete popup.

**Comment by cgrail** [comment]
Thanks. Good bug. Unfortunately I currently don't have time to fix it. Can somebody please fix it?
