### ISSUE TITLE
support for zenhub

### ISSUE THREAD

**Issue by Finkes** [cgrail/github-chrome-fullname#36]
We are using zenhub which is providing a kanban board based on GitHub issues. There are two hosted zenhub instances within our company. Would it be possible to extend this plugin for zenhub somehow? It's really annoying to not be able to see the real name of the people assigned to those issues.

**Comment by cgrail** [comment]
It's already available here: https://chrome.google.com/webstore/detail/sap-zenhub-name-instead-o/lmoocgmechihlpnfkojongpajapodjpm?hl=de&authuser=0
