### ISSUE TITLE
[Suggestion] IntelliJ plugin

### ISSUE THREAD

**Issue by payne911** [cgrail/github-chrome-fullname#49]
This is a wonderful extension, thanks to the creators/contributors!

I think it would be amazing to have an IntelliJ plugin that does the same thing when looking into the `Git Log` UI.

P.S. If [`GitHub Discussions`](https://docs.github.com/en/discussions) were activated for this repository, I would've created this under there.

**Comment by cgrail** [comment]
Sounds like a great idea. But I don’t have the time to implement this. And it’s also nothing like a quick Port. The Chrome extension is written in JavaScript. An IntelliJ plug-in would need a complete new implementation and I’m not even sure if IntelliJ allows this kind of extensions.
