### ISSUE TITLE
ZenHub Support

### ISSUE THREAD

**Issue by vlerenc** [cgrail/github-chrome-fullname#9]
Thank you for your great plugin Christian!

A question, since lately we are using [ZenHub](https://www.zenhub.com/), an extension for GitHub that puts project management capabilities on top of standard GitHub issues. It's quite neat and fits much better than Jira.

However, when working with it, one sees only the photos and the D/I-numbers. It would be great, if your plugin could also help with them in ZenHub.

In case you are interested, here some information:
* SAP ZenHub Information: https://github.wdf.sap.corp/zenhub/zenhub
* SAP ZenHub Board: https://zenhub.mo.sap.corp
* Contact: via SAP e-mail

**Comment by cgrail** [comment]
The SAP Zenhub version of the Extension is now available on the Chrome Webstore:
https://chrome.google.com/webstore/detail/sap-zenhub-name-instead-o/lmoocgmechihlpnfkojongpajapodjpm

**Comment by cgrail** [comment]
The code is available in the following branch:
https://github.com/cgrail/github-chrome-fullname/tree/zenhub

Thanks again to @Pfeifenjoy
